source 'https://cdn.cocoapods.org/'
source 'https://github.com/piratehacker/Specs.git'

pod 'piratehacker_GoogleSignIn', :path => '../../../', :testspecs => ['unit']
pod 'GoogleSignInSwiftSupport', :path => '../../../', :testspecs => ['unit']
project 'DaysUntilBirthdayForPod.xcodeproj'

target 'DaysUntilBirthdayForPod (iOS)' do
  platform :ios, '14.0'
end

target 'DaysUntilBirthdayForPod (macOS)' do
  platform :osx, '11.0'
end
